version: "3.8"
services:
    rabbitmq:
        image: rabbitmq:3-management
        container_name: rabbitmq
        ports:
            - 15672:15672
            - 5672:5672
        healthcheck:
            test: ["CMD", "rabbitmqctl", "status"]
            interval: 10s
            timeout: 3s
            retries: 5


    server:
        image: annabogacheva/server_mafia_new
        container_name: server
        environment:
            POSTGRES_DB: postgres
            POSTGRES_SERVER: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: postgres
            DB_HOST: postgres
        ports:
            - "8080:8080/tcp"
        depends_on:
            rabbitmq:
                condition: service_healthy
            postgres:
                condition: service_started

    rabbitmqserver:
        image: annabogacheva/server_mafia_rbmq
        restart: on-failure
        depends_on:
            - rabbitmq
            - server
        ports:
            - "7070:7070/tcp"

    postgres:
        build: ./postgres
        container_name: postgres
        restart: unless-stopped
        environment:
            POSTGRES_DB: postgres
            POSTGRES_SERVER: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: postgres
            DB_HOST: postgres
        volumes:
            - pg-data:/var/lib/postgresql/data
        ports:
            - "5432:5432/tcp"

    rest:
        image: annabogacheva/server_mafia_rest
        restart: on-failure
        depends_on:
            - postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_SERVER: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
            DB_USER: postgres
            DB_PASSWORD: postgres
            DB_NAME: postgres
            DB_HOST: postgres
        ports:
            - "5050:5050/tcp"


volumes:
    pg-data: