version: "3"
services:
    rabbitmq:
        image: rabbitmq:3-management
        ports:
            - "15672:15672"
            - "5672:5672"
    server:
        image: annabogacheva/server_mafia_rpc
        ports:
            - "8080:8080/tcp"
    rabbitmqserver:
        image: annabogacheva/server_mafia_rbmq
        restart: on-failure
        depends_on:
            - rabbitmq
            - server
        ports:
            - "7070:7070/tcp"
